name: Testing stuff

on:
  push:
    branches:
      - skip-test

jobs:
  a_test_job:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
      - name: commit messages
        run: |

          COMMIT_MESSAGES = ${{ join(github.event.commits.*.message, ' ') }}
          echo "$COMMIT_MESSAGES"
        # if: ${{ contains(github.event.commits.*.message.join(" "), "skip") }}
        # run: echo "includes substring skip"